service: import-service
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  region: ${env:REGION}
  stage: dev

  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::aws-shop-imported-files"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::aws-shop-imported-files/*"

plugins:
  - serverless-plugin-webpack
  - serverless-dotenv-plugin

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: import
          method: get
          request:
            parameters:
              querystrings:
                name: true
          cors: true

  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: aws-shop-imported-files
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
